<?php

/**
 * @file
 * Contains paragraphs_report.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paragraphs_report_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paragraphs_report module.
    case 'help.page.paragraphs_report':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Get an inventory of paragraphs in use.') . '</p>';
      return $output;

    default:
  }
}
